### ISSUE TITLE
1.2.1 异常:Call to undefined method League\Flysystem\Filesystem::url

### ISSUE THREAD

**Issue by yl** [overtrue/laravel-ueditor#18]
laravel 5.1.*
本地文件上传成功，但页面显示报错

```
[2017-05-22 11:06:48] local.ERROR: BadMethodCallException: Call to undefined method League\Flysystem\Filesystem::url in /vendor/league/flysystem/src/Plugin/PluggableTrait.php:90
Stack trace:
#0 [internal function]: League\Flysystem\Filesystem->__call('url', Array)
#1 /vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(350): call_user_func_array(Array, Array)
#2 /vendor/overtrue/laravel-ueditor/src/StorageManager.php(64): Illuminate\Filesystem\FilesystemAdapter->__call('url', Array)
#3 /vendor/overtrue/laravel-ueditor/src/UEditorController.php(43): Overtrue\LaravelUEditor\StorageManager->upload(Object(Illuminate\Http\Request))
#4 [internal function]: Overtrue\LaravelUEditor\UEditorController->serve(Object(Illuminate\Http\Request))
#5 /vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#6 /vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('serve', Array)
#7 /vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Overtrue\LaravelUEditor\UEditorController), Object(Illuminate\Routing\Route), 'serve')
#8 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 /vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Overtrue\LaravelUEditor\UEditorController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'serve')
#14 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Overtrue\\Larave...', 'serve')
#15 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#16 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(673): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#23 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#24 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#26 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 /vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#30 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#33 /vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#36 /vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#39 /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#42 /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#45 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#48 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#52 /public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#53 /server.php(21): require_once('/...')
#54 {main}  

```

**Comment by overtrue** [comment]
这 TM 尴尬了，5.1 的 FilesystemAdapter 与 新版差别好大。。。

**Comment by overtrue** [comment]
请使用 dev-master 版本尝试一下

**Comment by yl** [comment]
```
{
"state": "SUCCESS",
"url": "/storage//uploads/image/2017/05/22/fdc4b9d482bebf092830f81e957ba6ef.jpeg",
"title": "/uploads/image/2017/05/22/fdc4b9d482bebf092830f81e957ba6ef.jpeg",
"original": "79A4264EC543FA417E3D31EB64FA9D2A.jpeg",
"type": "",
"size": 82350
}
```

url 有误

**Comment by overtrue** [comment]
没问题吧

**Comment by yl** [comment]
多了个 /

**Comment by overtrue** [comment]
更新一下

**Comment by yl** [comment]
🤣 `/storage` 下文件不能直接访问

**Comment by overtrue** [comment]
```shell
$ php artisan storage:link
```

**Comment by yl** [comment]
5.1 没有这个命令，手动 ln -s /storage/uploads /public 也不行

**Comment by overtrue** [comment]
```shell
$ ln -s `pwd`/storage/app/public `pwd`/public/storage 
```

**Comment by yl** [comment]
localhost:8000/ueditor/server?action=list-image

Call to undefined method League\Flysystem\Filesystem::url

**Comment by overtrue** [comment]
你想让我访问你的本地地址么 ...

**Comment by overtrue** [comment]
```shell
$ composer update overtrue/laravel-ueditor -vvv
```

**Comment by overtrue** [comment]
?

**Comment by yangliulnn** [comment]
上传到本地没有问题，上传到七牛云失败。

server?action=upload-image 返回成功，但七牛云中并没有相应文件。

**Comment by yl** [comment]
暂未发现其他问题，辛苦了。👍

**Comment by jiker-burce** [comment]
我把安兄的\StorageManager.php重写了，具体内容如下（可以解决上面所有问题，可能代码不是很优美），我修改了几处，同时添加了一个在这个类中添加了一个url方法(因为5.1中FilesystemAdapter 是没有url方法的)，以下全部是修改后内容：
upload(Request $request)
'url' => $this->url($filename),

添加url()方法
```
public function url($path)
{
    $adapter = $this->disk->getDriver()->getAdapter();
    if (method_exists($adapter, 'getUrl')) {
        return $adapter->getUrl($path);
    } elseif ($adapter instanceof QiniuAdapter) {
        $config = config('filesystems.disks.qiniu');
        if (array_key_exists("domain",$config)) {
            return "http://" . $config['domain'] . '/'. $path;
        }
        $path = '/storage/'.$path;
        return Str::contains($path, '/storage/public/') ?
            Str::replaceFirst('/public/', '/', $path) : $path;
    } else {
        throw new RuntimeException('This driver does not support retrieving URLs.');
    }
}
```
修改paginateFiles（）方法
'url' => $this->url($file['path']),

修改store（）方法
if(method_exists($this->disk,'putFileAs')){
    return $this->disk->putFileAs('', $file, $filename);
}else{
    $realPath = $file->getRealPath();
    return $this->disk->put($filename,file_get_contents($realPath));
}

**Comment by overtrue** [comment]
已在 dev-master 实现这些方法了

**Comment by jiker-burce** [comment]
更新到dev-maser了，更新到dev-master了，用七牛的话，报下面异常：
点击“在线管理”：
```
[2017-05-22 12:08:46] local.ERROR: RuntimeException: This driver does not support retrieving URLs. in H:\wamp\www\gdyxh\vendor\overtrue\laravel-ueditor\src\UrlResolverTrait.php:54
Stack trace:
#0 H:\wamp\www\gdyxh\vendor\overtrue\laravel-ueditor\src\UrlResolverTrait.php(33): Overtrue\LaravelUEditor\StorageManager->url('uploads/image/2...')
#1 H:\wamp\www\gdyxh\vendor\overtrue\laravel-ueditor\src\StorageManager.php(111): Overtrue\LaravelUEditor\StorageManager->getUrl('uploads/image/2...')
#2 [internal function]: Overtrue\LaravelUEditor\StorageManager->Overtrue\LaravelUEditor\{closure}(Array, 0)
#3 H:\wamp\www\gdyxh\vendor\laravel\framework\src\Illuminate\Support\Collection.php(469): array_map(Object(Closure), Array, Array)
#4 H:\wamp\www\gdyxh\vendor\overtrue\laravel-ueditor\src\StorageManager.php(114): Illuminate\Support\Collection->map(Object(Closure))
#5 H:\wamp\www\gdyxh\vendor\overtrue\laravel-ueditor\src\StorageManager.php(88): Overtrue\LaravelUEditor\StorageManager->paginateFiles(Array, '0', '20')
#6 H:\wamp\www\gdyxh\vendor\overtrue\laravel-ueditor\src\UEditorController.php(35): Overtrue\LaravelUEditor\StorageManager->listFiles('/uploads/image/', '0', '20', Array)
#7 [internal function]: Overtrue\LaravelUEditor\UEditorController->serve(Object(Illuminate\Http\Request))
#8 H:\wamp\www\gdyxh\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(256): call_user_func_array(Array, Array)
```
点击图片上传按钮报：
```
[2017-05-22 12:14:48] local.ERROR: RuntimeException: This driver does not support retrieving URLs. in H:\wamp\www\gdyxh\vendor\overtrue\laravel-ueditor\src\UrlResolverTrait.php:54
Stack trace:
#0 H:\wamp\www\gdyxh\vendor\overtrue\laravel-ueditor\src\UrlResolverTrait.php(33): Overtrue\LaravelUEditor\StorageManager->url('/uploads/image/...')
#1 H:\wamp\www\gdyxh\vendor\overtrue\laravel-ueditor\src\StorageManager.php(66): Overtrue\LaravelUEditor\StorageManager->getUrl('/uploads/image/...')
#2 H:\wamp\www\gdyxh\vendor\overtrue\laravel-ueditor\src\UEditorController.php(43): Overtrue\LaravelUEditor\StorageManager->upload(Object(Illuminate\Http\Request))
#3 [internal function]: Overtrue\LaravelUEditor\UEditorController->serve(Object(Illuminate\Http\Request))
#4 H:\wamp\www\gdyxh\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(256): call_user_func_array(Array, Array)
#5 H:\wamp\www\gdyxh\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('serve', Array)
#6 H:\wamp\www\gdyxh\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Overtrue\LaravelUEditor\UEditorController), Object(Illuminate\Routing\Route), 'serve')
#7 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
```

**Comment by overtrue** [comment]
你的七牛用的哪个提供的 adapter?什么版本？

**Comment by jiker-burce** [comment]
用你写的 "overtrue/laravel-filesystem-qiniu": "^0.0.1",
谢谢关注。

**Comment by overtrue** [comment]
https://github.com/overtrue/flysystem-qiniu/blob/master/src/QiniuAdapter.php#L220

**Comment by jiker-burce** [comment]
发现问题所在了。
"overtrue/flysystem-qiniu": "^0.0.2",
"overtrue/laravel-filesystem-qiniu": "^0.0.2",
这2个插件包都需要更新到0.02版。
